# Generated by Django 2.2.8 on 2019-12-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='main_tag',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
