# Generated by Django 2.2.8 on 2020-01-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tag_main_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='main_tag',
        ),
        migrations.AddField(
            model_name='article',
            name='main_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.Tag', verbose_name='Основная категория'),
            preserve_default=False,
        ),
    ]
