# Generated by Django 2.2.8 on 2020-01-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200102_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='main_tag',
        ),
    ]
