# Generated by Django 2.2.8 on 2020-01-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_main_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
